### PR TITLE
Update UI post, fix comment, fix hover action

### LINKED ISSUE #24: Light mode button background color looks bad when hovered
image

est: 10m

### PR DESCRIPTION
**Pull request by DucNV9203**
Resolve #24 , #3 
image
image
image
image

### CODE REVIEW

File: frontend/src/components/CreatePost.jsx [hunk 1]
```diff
@@ -95,72 +102,109 @@ const CreatePost = () => {
         display={"flex"}
         gap={10}
         mt={4}
-        mb={8}
+        // mb={8}
```
Comment (PhenChua29) [inline frontend/src/components/CreatePost.jsx:105]:
```suggestion
```

Delete this if not used.

File: frontend/src/components/CreatePost.jsx [hunk 2]
```diff
@@ -95,72 +102,109 @@ const CreatePost = () => {
...
+                  ref={textareaRef}
+                  variant="unstyled"
+                  placeholder="What's new?"
+                  onChange={handleTextChange}
+                  value={postText}
+                  overflow="hidden"
+                  resize={"none"}
+                  minHeight={"30px"}
+                  rows={1}
+                  // lineHeight={"20px"}
```
Comment (PhenChua29) [inline frontend/src/components/CreatePost.jsx:151]:
```suggestion
```

Delete this if it is not used.

File: frontend/src/components/UpdateProfileModal.jsx [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+  }, []);
+
+  return (
+    <>
+      <Button
+        w={"full"}
+        bg={"none"}
+        border={"groove 0.2px grey"}
+        // borderColor={useColorModeValue("white", "gray")}
+        // bg={useColorModeValue("white", "dark")}
```
Comment (PhenChua29) [inline frontend/src/components/UpdateProfileModal.jsx:83]:
```suggestion
```

Delete this if it is not used.

File: frontend/src/components/UpdateProfileModal.jsx [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+            <Flex justify="space-between" w="full" pb={3}>
+              <FormLabel mb="0">Private profile</FormLabel>
+              <Switch
+                isChecked={inputs.privateProfile}
+                onChange={(e) => setInputs({ ...inputs, privateProfile: e.target.checked })}
+                size='lg'
+                colorScheme={useColorModeValue("blackAlpha", "whiteAlpha")}
+              />
+            </Flex>
+          </FormControl> */}
```
Comment (PhenChua29) [inline frontend/src/components/UpdateProfileModal.jsx:149]:
```suggestion
```

Delete this if it is not used.

File: frontend/src/components/UserHeader.jsx [hunk 5]
```diff
@@ -8,9 +8,10 @@ import { BsInstagram } from "react-icons/bs";
 import useShowToast from "../hooks/useShowToast";
 import { useRecoilValue } from "recoil";
 import userAtom from "../atoms/userAtom";
-import { Link as RouterLink } from "react-router-dom";
+// import { Link as RouterLink } from "react-router-dom";
```
Comment (PhenChua29) [inline frontend/src/components/UserHeader.jsx:11]:
```suggestion
```

Delete this if it is not used.

File: frontend/src/components/UserHeader.jsx [hunk 6]
```diff
@@ -98,13 +99,16 @@ const UserHeader = ({ user }) => {
           </Box>
         </Flex>
       </Flex>
-      {currentUser?._id === user._id && (
+      {/* {currentUser?._id === user._id && (
         <Link as={RouterLink} to="/update">
           <Button bg={"none"} border={"groove 0.2px grey"} width={"588px"}>
           {t('update_profile')}
           </Button>
         </Link>
```
Comment (PhenChua29) [inline frontend/src/components/UserHeader.jsx:107]:
```suggestion
```

Delete this if it is not used.

File: frontend/src/components/UserHeader.jsx [hunk 7]
```diff
@@ -98,13 +99,16 @@ const UserHeader = ({ user }) => {
...
-      )}
+      )} */}
```
Comment (PhenChua29) [inline frontend/src/components/UserHeader.jsx:108]:
```suggestion
```

Delete this if it is not used.

**Review by PhenChua29 — APPROVED** [review]
Great!
